name: Build and Publish plugin
on:
  push:
    paths-ignore:
      - 'LICENSE'


jobs:
  Publish:
    name: Publish
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies and build 🔧
        run: |
          TAG=$(git describe --tags)
          echo "TAG=${TAG}" >> $GITHUB_ENV
          jq '.version="'$TAG'"' package.json > package.json.new
          mv package.json.new package.json
          npm i

      - name: Upload to Github
        if: startsWith(github.ref, 'refs/tags')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          release_name: ${{ env.TAG }}
          overwrite: true
          file_glob: true
      
      - name: Publish on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}